services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker_compose_volumes/postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2
    container_name: redis
    environment:
      REDIS_PASSWORD: redis
    ports:
      - "6379:6379"
    volumes:
      - ./docker_compose_volumes/redis_data:/data

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      SERVICES: s3,sqs,sns,lambda,dynamodb
      PERSISTENCE: /tmp/localstack_data
    ports:
      - "4566:4566"
      - "4571:4571"
    volumes:
      - ./docker_compose_volumes/localstack_data:/tmp/localstack_data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/config/servers.json
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - ./docker_compose_volumes/pgadmin_data:/var/lib/pgadmin
      - ./docker_compose_volumes/pgadmin_config:/pgadmin4/config
      - ./docker_compose_volumes/pgadmin_config/servers.json:/pgadmin4/config/servers.json
    

volumes:
  postgres_data:
  redis_data:
  localstack_data:
